language: java
jdk:
- oraclejdk8
# GitHub strips the wrapper jar file so we have to force its download during the build
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
- ./mvnw clean install
- ./mvnw sonar:sonar   -Dsonar.organization=gdiazs-github   -Dsonar.host.url=https://sonarcloud.io   -Dsonar.login=727ddb69e056fa3ecbfb89b3e484671306714a36
